import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { atomicWrite, exists } from '../utils/fs.js';
import { resolveProjectRoot } from '../context/paths.js';

const adrRelative = '.ai-workflow/adr';
const adrFilePattern = /^(\d{4})-.+\.md$/;
const banner = '<!-- Generated by `ai-workflow adr index`; do not edit by hand. -->';
const empty = '-';

export interface AdrEntry {
  number: string;
  status: string;
  date: string;
  supersedes: string;
  supersededBy: string;
  summary: string;
}

export interface AdrIndexReport {
  index: string;
  count: number;
}

export interface AdrIndexVerification extends AdrIndexReport {
  consistent: boolean;
}

export function adrDirectory(project: string): string {
  return join(resolveProjectRoot(project), adrRelative);
}

export function adrIndexPath(project: string): string {
  return join(adrDirectory(project), 'INDEX.md');
}

function headerField(header: string, name: string): string {
  const match = new RegExp(`^${name}:[ \\t]*(.*)$`, 'm').exec(header);
  return match?.[1]?.trim() ?? '';
}

function cell(value: string): string {
  return value ? value.replace(/\|/g, '\\|') : empty;
}

export async function readAdrEntries(project: string): Promise<AdrEntry[]> {
  const directory = adrDirectory(project);
  if (!(await exists(directory))) return [];
  const entries: AdrEntry[] = [];
  for (const name of (await readdir(directory)).sort()) {
    const match = adrFilePattern.exec(name);
    if (!match) continue;
    const source = await readFile(join(directory, name), 'utf8');
    const header = source.split(/\r?\n##[ \t]/)[0] ?? source;
    const status = headerField(header, 'Status');
    const [statusToken = '', supersededBy = ''] = status.split(/\s+/);
    entries.push({
      number: match[1] as string,
      status: statusToken,
      date: headerField(header, 'Date'),
      supersedes: headerField(header, 'Supersedes'),
      supersededBy: statusToken === 'superseded-by' ? supersededBy : '',
      summary: headerField(header, 'Summary')
    });
  }
  return entries.sort((left, right) => left.number.localeCompare(right.number));
}

export function renderAdrIndex(entries: AdrEntry[]): string {
  const rows = entries.map((entry) => `| ${entry.number} | ${cell(entry.status)} | ${cell(entry.date)} | ${cell(entry.supersedes)} | ${cell(entry.supersededBy)} | ${cell(entry.summary)} |`);
  return [banner, '', '# ADR index', '', '| # | Status | Date | Supersedes | Superseded-by | Summary |', '| --- | --- | --- | --- | --- | --- |', ...rows, ''].join('\n');
}

export async function generateAdrIndex(project: string): Promise<AdrIndexReport> {
  const root = resolveProjectRoot(project);
  const entries = await readAdrEntries(root);
  const index = adrIndexPath(root);
  await atomicWrite(index, renderAdrIndex(entries));
  return { index, count: entries.length };
}

export async function verifyAdrIndex(project: string): Promise<AdrIndexVerification> {
  const root = resolveProjectRoot(project);
  const entries = await readAdrEntries(root);
  const index = adrIndexPath(root);
  const present = await exists(index);
  const consistent = entries.length === 0 && !present ? true : present && (await readFile(index, 'utf8')) === renderAdrIndex(entries);
  return { index, count: entries.length, consistent };
}
