import { execFile } from 'node:child_process';
import { lstat, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { promisify } from 'node:util';
const exec = promisify(execFile);

const forbidden = new Set(['push', 'pull', 'fetch', 'rebase', 'reset', 'clean', 'stash', 'tag']);
export async function git(project: string, args: string[]): Promise<string> { if (args[0] && forbidden.has(args[0])) throw new Error(`Git operation is forbidden: ${args[0]}`); const { stdout } = await exec('git', args, { cwd: project, maxBuffer: 1_000_000 }); return stdout.trim(); }
export async function gitBaseline(project: string): Promise<{ branch: string; head: string | null; status: string }> { const branch = await git(project, ['branch', '--show-current']); let head: string | null = null; try { head = await git(project, ['rev-parse', 'HEAD']); } catch { /* unborn HEAD */ } return { branch, head, status: await git(project, ['status', '--porcelain=v1']) }; }
export interface Worktree { path: string; branch: string; base: string }
function safeName(value: string): string { return value.replace(/[^a-zA-Z0-9_-]/g, '-'); }
export async function createPlanWorktree(project: string, runId: string, baseBranch: string, baseHead?: string | null): Promise<Worktree> { const path = resolve(project, '.ai-workflow/runs', runId, 'plan-worktree'); const branch = `ai-workflow/${safeName(runId)}/plan`; await mkdir(resolve(project, '.ai-workflow/runs', runId), { recursive: true }); const base = baseHead ?? await git(project, ['rev-parse', baseBranch]); await git(project, ['worktree', 'add', '-b', branch, path, base]); return { path, branch, base }; }
export async function createTaskWorktree(project: string, plan: Worktree, runId: string, taskId: string): Promise<Worktree> { const path = resolve(project, '.ai-workflow/runs', runId, `task-${safeName(taskId)}`); const branch = `ai-workflow/${safeName(runId)}/${safeName(taskId)}`; await git(plan.path, ['worktree', 'add', '-b', branch, path, plan.branch]); return { path, branch, base: plan.branch }; }
export async function commitTask(worktree: string, taskId: string, paths: string[]): Promise<string> { if (!paths.length) throw new Error(`Task ${taskId} has no write scope`); const present: string[] = []; for (const path of paths) { try { await lstat(resolve(worktree, path)); present.push(path); } catch { /* an empty task may still have a recorded commit */ } } if (present.length) await git(worktree, ['add', '--', ...present]); await git(worktree, ['commit', '--allow-empty', '-m', `ai-workflow: ${taskId}`]); return git(worktree, ['rev-parse', 'HEAD']); }
export async function mergeTask(planPath: string, commit: string): Promise<string> { await git(planPath, ['merge', '--no-ff', '--no-edit', commit]); return git(planPath, ['rev-parse', 'HEAD']); }
export async function integratePlan(project: string, planBranch: string, targetBranch: string, expectedHead?: string | null): Promise<string> { const current = await git(project, ['rev-parse', targetBranch]); if (expectedHead !== undefined && current !== expectedHead) throw new Error(`Git baseline drift: expected ${expectedHead}, got ${current}`); await git(project, ['merge', '--no-ff', '--no-edit', planBranch]); return git(project, ['rev-parse', 'HEAD']); }
export async function removeOwnedWorktrees(project: string, paths: string[]): Promise<void> { for (const path of paths) { try { await git(project, ['worktree', 'remove', '--force', path]); } catch (error) { if (!String(error).includes('not a working tree')) throw error; } } }
export async function deleteOwnedBranches(project: string, branches: string[]): Promise<void> { for (const branch of branches) { try { await git(project, ['branch', '-D', branch]); } catch { /* already removed */ } } }
