import { describe, expect, it } from 'vitest';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { temporary } from '../helpers.js';

const exec = promisify(execFile);
const cli = ['exec', 'tsx', 'src/cli.ts'] as const;

const EXPECTED = [
  '<!-- Generated by `ai-workflow adr index`; do not edit by hand. -->',
  '',
  '# ADR index',
  '',
  '| # | Status | Date | Supersedes | Superseded-by | Summary |',
  '| --- | --- | --- | --- | --- | --- |',
  '| 0001 | accepted | 2026-01-01 | - | - | First decision |',
  '| 0002 | superseded-by | 2026-01-02 | - | ADR-0003 | Second decision |',
  '| 0003 | accepted | 2026-01-03 | ADR-0002 | - | Third decision |',
  '',
].join('\n');

async function fixture(): Promise<string> {
  const root = await temporary('ai-workflow-adr-index-');
  const directory = join(root, '.ai-workflow/adr');
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, '0003-third-decision.md'), '# 0003 Third decision\n\nStatus: accepted\nDate: 2026-01-03\nSummary: Third decision\nSupersedes: ADR-0002\n\n## Context\n\nThird.\n');
  await writeFile(join(directory, '0001-first-decision.md'), '# 0001 First decision\n\nStatus: accepted\nDate: 2026-01-01\nSummary: First decision\n\n## Context\n\nFirst.\n');
  await writeFile(join(directory, '0002-second-decision.md'), '# 0002 Second decision\n\nStatus: superseded-by ADR-0003\nDate: 2026-01-02\nSummary: Second decision\n\n## Context\n\nSecond.\n');
  await writeFile(join(directory, 'notes.md'), 'arbitrary notes\n');
  return root;
}

describe('adr index CLI', () => {
  it('generates a deterministic index from ADR headers and ignores non-ADR files', async () => {
    const project = await fixture();

    const { stdout } = await exec('pnpm', [...cli, 'adr', 'index', '--project', project]);
    const report = JSON.parse(stdout) as { index: string; count: number };

    expect(report.count).toBe(3);
    expect(report.index).toBe(join(project, '.ai-workflow/adr/INDEX.md'));
    expect(await readFile(report.index, 'utf8')).toBe(EXPECTED);
    expect(await readFile(report.index, 'utf8')).not.toContain('notes');
  });

  it('sorts entries by number regardless of file creation order', async () => {
    const project = await fixture();

    await exec('pnpm', [...cli, 'adr', 'index', '--project', project]);
    const first = await readFile(join(project, '.ai-workflow/adr/INDEX.md'), 'utf8');
    await exec('pnpm', [...cli, 'adr', 'index', '--project', project]);
    const second = await readFile(join(project, '.ai-workflow/adr/INDEX.md'), 'utf8');

    expect(first).toBe(EXPECTED);
    expect(second).toBe(first);
  });

  it('verifies a matching index and rejects a drifted one', async () => {
    const project = await fixture();
    const indexPath = join(project, '.ai-workflow/adr/INDEX.md');

    await exec('pnpm', [...cli, 'adr', 'index', '--project', project]);
    const { stdout } = await exec('pnpm', [...cli, 'adr', 'index', '--project', project, '--verify']);
    expect(JSON.parse(stdout)).toMatchObject({ consistent: true, count: 3 });

    await writeFile(indexPath, '# hand-edited\n');
    await expect(exec('pnpm', [...cli, 'adr', 'index', '--project', project, '--verify'])).rejects.toThrow();
  });

  it('reports inconsistency when the index is missing but ADRs exist', async () => {
    const project = await fixture();

    await expect(exec('pnpm', [...cli, 'adr', 'index', '--project', project, '--verify'])).rejects.toThrow();
  });

  it('accepts a project with no ADRs when no index exists', async () => {
    const project = await temporary('ai-workflow-adr-empty-');

    const { stdout } = await exec('pnpm', [...cli, 'adr', 'index', '--project', project, '--verify']);
    expect(JSON.parse(stdout)).toMatchObject({ consistent: true, count: 0 });
  });
});
