import { describe, expect, it } from 'vitest';
import { join } from 'node:path';
import { writeJson } from '../../src/utils/fs.js';
import { generateWorkflow } from '../../src/workflow/generate.js';
import { approveWorkflow } from '../../src/workflow/approval.js';
import { cancelRun, cleanupRun, resumeRun, startRun } from '../../src/runtime/runner.js';
import { exists } from '../../src/utils/fs.js';
import { frozenPlan, gitInit, temporary } from '../helpers.js';
const done = { status: 'done' as const, summary: 'ok', changed_paths: [] as string[], evidence: [] as string[], tests: [], findings: [], git_refs: [], support_requests: [] as string[] };

describe('runtime lifecycle', () => {
  it('requires a matching receipt and completes nodes idempotently', async () => { const root = await temporary(); await gitInit(root); const plan = await frozenPlan(root); const workflow = await generateWorkflow(plan, 'codex'); const path = join(plan, 'workflow.json'); await writeJson(path, workflow); await expect(startRun({ workflowPath: path, host: 'codex', project: root })).rejects.toThrow(/receipt/); await approveWorkflow(path, root); const calls: string[] = []; const run = await startRun({ workflowPath: path, host: 'codex', project: root, executor: async (id, context) => { calls.push(id); if (id.endsWith('-implement')) { await (await import('node:fs/promises')).mkdir(join(context.cwd, 'src'), { recursive: true }); await (await import('node:fs/promises')).writeFile(join(context.cwd, 'src/output.ts'), 'done'); } return done; } }); expect(run.state).toBe('complete'); expect(calls.length).toBeGreaterThan(0); expect(await exists(join(root, '.ai-workflow/runs', run.run_id, 'summary.md'))).toBe(true); await cleanupRun(root, run.run_id); expect(await exists(join(root, '.ai-workflow/runs', `${run.run_id}.final.json`))).toBe(true); });
  it('pauses after retries and resumes without repeating success', async () => { const root = await temporary(); await gitInit(root); const plan = await frozenPlan(root); const workflow = await generateWorkflow(plan, 'claude'); workflow.nodes.find((node) => node.id.endsWith('-explore'))!.retry = 0; const path = join(plan, 'workflow.json'); await writeJson(path, workflow); await approveWorkflow(path, root); let failed = false; const run = await startRun({ workflowPath: path, host: 'claude', project: root, executor: async (id, context) => { if (!failed && id.endsWith('-explore')) { failed = true; throw new Error('boom'); } if (id.endsWith('-implement')) { await (await import('node:fs/promises')).mkdir(join(context.cwd, 'src'), { recursive: true }); await (await import('node:fs/promises')).writeFile(join(context.cwd, 'src/output.ts'), 'done'); } return done; } }); expect(run.state).toBe('paused'); const resumed = await resumeRun(root, run.run_id, async (id, context) => { if (id.endsWith('-implement')) { await (await import('node:fs/promises')).mkdir(join(context.cwd, 'src'), { recursive: true }); await (await import('node:fs/promises')).writeFile(join(context.cwd, 'src/output.ts'), 'done'); } return done; }); expect(resumed.state).toBe('complete'); });
  it('cancels and then permits cleanup', async () => { const root = await temporary(); await gitInit(root); const plan = await frozenPlan(root); const workflow = await generateWorkflow(plan, 'opencode'); const path = join(plan, 'workflow.json'); await writeJson(path, workflow); await approveWorkflow(path, root); const run = await startRun({ workflowPath: path, host: 'opencode', project: root, defer: true }); const cancelled = await cancelRun(root, run.run_id); expect(cancelled.state).toBe('cancelled'); await cleanupRun(root, run.run_id); });
});
