import { readPlan, readTasks } from './parse.js';
import type { Host, Workflow, Node, TaskDocument } from './types.js';
import { objectDigest } from '../utils/hash.js';
import { scopesOverlap } from '../utils/paths.js';
import { validateWorkflow } from './validate.js';

const roleBySurface: Record<string, Node['role']> = { backend: 'backend', frontend: 'frontend', docs: 'backend', 'cross-stack': 'task-worker' };
const base = { timeout_ms: 3600000, retry: 2, result_schema: 'schemas/result.schema.json' as const, on_failure: 'pause' as Node['on_failure'] };
function node(value: Omit<Node, keyof typeof base> & Partial<typeof base>): Node { return { ...base, ...value }; }
function broadOrUnknown(task: TaskDocument): boolean { return task.writeScope.length === 0 || task.writeScope.some((path) => !path.includes('/') && !path.includes('.')); }
function serializeConflicts(tasks: TaskDocument[]): TaskDocument[] { const result = structuredClone(tasks); for (let index = 0; index < result.length; index++) { const current = result[index]; if (!current) continue; for (let earlier = 0; earlier < index; earlier++) { const previous = result[earlier]; if (!previous) continue; if ((broadOrUnknown(current) || broadOrUnknown(previous) || scopesOverlap(current.writeScope, previous.writeScope)) && !current.dependsOn.includes(previous.id)) current.dependsOn.push(previous.id); } } return result; }
function taskNodes(task: TaskDocument, planScope: string): Node[] { const prefix = task.id; const dependencyCommits = task.dependsOn.map((dependency) => `${dependency}-commit`); const screenshot = `${planScope}/screenshot`; return [
  node({ id: `${prefix}-setup`, phase: 'plan_setup', kind: 'git', role: 'git-operator', task_id: task.id, depends_on: dependencyCommits, read_scope: [planScope], write_scope: [], allowed_commands: ['git worktree add'] }),
  node({ id: `${prefix}-explore`, phase: 'executing', kind: 'agent', role: 'file-explorer', task_id: task.id, depends_on: [`${prefix}-setup`], read_scope: [...new Set([planScope, ...task.readScope])], write_scope: [], allowed_commands: [] }),
  node({ id: `${prefix}-coordinate`, phase: 'executing', kind: 'pipeline', role: 'task-worker', task_id: task.id, depends_on: [`${prefix}-explore`], read_scope: [planScope], write_scope: [], allowed_commands: [] }),
  node({ id: `${prefix}-implement`, phase: 'executing', kind: 'agent', role: roleBySurface[task.surface] ?? 'task-worker', task_id: task.id, depends_on: [`${prefix}-coordinate`], read_scope: [...new Set([...task.readScope, ...task.writeScope])], write_scope: task.writeScope, allowed_commands: task.testCommands }),
  node({ id: `${prefix}-test`, phase: 'validating', kind: 'agent', role: 'test', task_id: task.id, depends_on: [`${prefix}-implement`], read_scope: [...new Set([...task.readScope, ...task.writeScope])], write_scope: [screenshot], allowed_commands: task.testCommands, on_failure: 'repair_once' }),
  node({ id: `${prefix}-commit`, phase: 'executing', kind: 'git', role: 'git-operator', task_id: task.id, depends_on: [`${prefix}-test`], read_scope: task.writeScope, write_scope: [], allowed_commands: ['git add', 'git commit', 'git merge', 'git worktree remove'] })
]; }

export async function generateWorkflow(planDirectory: string, host: Host, concurrency = 3): Promise<Workflow> {
  const plan = await readPlan(planDirectory); const parsedTasks = await readTasks(planDirectory); const planScope = `ai-workflow/plans/${plan.planId}`; const tasks = serializeConflicts(parsedTasks.length ? parsedTasks : [{ id: 'task-001-plan', requirements: plan.requirements, acceptanceCriteria: plan.acceptanceCriteria, dependsOn: [], surface: 'cross-stack', readScope: [`${planScope}/spec.md`, `${planScope}/plan.md`], writeScope: [], testCommands: [], path: `${planScope}/plan.md` }]);
  const nodes = tasks.flatMap((task) => taskNodes(task, planScope)); const commits = tasks.map((task) => `${task.id}-commit`); const changed = [...new Set(tasks.flatMap((task) => task.writeScope))];
  nodes.push(node({ id: 'plan-validate', phase: 'validating', kind: 'gate', role: 'test', depends_on: commits, read_scope: changed.length ? changed : [planScope], write_scope: [`${planScope}/screenshot`], allowed_commands: [] }), node({ id: 'standards-review', phase: 'reviewing', kind: 'agent', role: 'standards-review', depends_on: ['plan-validate'], read_scope: ['MEMORY.md', ...changed], write_scope: [], allowed_commands: [], retry: 0 }), node({ id: 'spec-review', phase: 'reviewing', kind: 'agent', role: 'spec-review', depends_on: ['plan-validate'], read_scope: [planScope, ...changed], write_scope: [], allowed_commands: [], retry: 0 }), node({ id: 'plan-integrate', phase: 'integrating', kind: 'git', role: 'git-operator', depends_on: ['standards-review', 'spec-review'], read_scope: changed.length ? changed : [planScope], write_scope: [], allowed_commands: ['git merge --no-ff', 'git worktree remove'], retry: 0 }));
  const workflow: Workflow = { schema_version: '1.0.0', plan_id: plan.planId, host, input_digests: { plan: plan.digest, tasks: objectDigest(parsedTasks) }, concurrency: Math.min(3, Math.max(1, concurrency)), policies: { max_retries: 2, default_timeout_ms: 3600000, repair_rounds: 1, push_allowed: false, rebase_allowed: false }, phases: ['preflight', 'baseline', 'plan_setup', 'executing', 'validating', 'reviewing', 'repairing', 'integrating'], nodes: nodes as [Node, ...Node[]], gates: [{ id: 'tests', after: ['plan-validate'], kind: 'tests-pass' }, { id: 'reviews', after: ['standards-review', 'spec-review'], kind: 'reviews-pass-or-repair' }, { id: 'integration', after: ['plan-integrate'], kind: 'baseline-stable' }] };
  const validation = await validateWorkflow(workflow); if (!validation.valid) throw new Error(`Generated workflow is invalid: ${validation.errors.join('; ')}`); return workflow;
}
export function applyAdjustments(workflow: Workflow, operations: Array<Record<string, unknown>>): Workflow { const result: Workflow = structuredClone(workflow); for (const operation of operations) { const op = String(operation.op); const target = result.nodes.find((item) => item.id === operation.node || item.task_id === operation.node); if (op === 'set-concurrency') result.concurrency = Number(operation.value); else if (target && op === 'set-role') target.role = String(operation.value) as Node['role']; else if (target && op === 'set-retry') target.retry = Number(operation.value); else if (target && op === 'set-failure-policy') target.on_failure = String(operation.value) as Node['on_failure']; else if (target && op === 'add-dependency') target.depends_on = [...new Set([...target.depends_on, String(operation.dependency)])]; else if (target && op === 'remove-dependency') target.depends_on = target.depends_on.filter((item) => item !== operation.dependency); else throw new Error(`Unsupported or unknown adjustment: ${op}`); } return result; }
export function explainWorkflow(workflow: Workflow): string { const lines = [`Plan: ${workflow.plan_id}`, `Host: ${workflow.host}`, `Concurrency: ${workflow.concurrency}`, `Nodes: ${workflow.nodes.length}`, `Input digests: ${JSON.stringify(workflow.input_digests)}`, '', '```mermaid', 'graph TD']; for (const item of workflow.nodes) { if (item.depends_on.length === 0) lines.push(`  ${item.id}[${item.role}]`); for (const dependency of item.depends_on) lines.push(`  ${dependency} --> ${item.id}`); } lines.push('```', '', 'Risks: scope violations, baseline drift, conflicts, host failures and failed gates pause the run.'); return lines.join('\n'); }
